name: CI Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}   # 수동 실행 버튼

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "event: ${{ github.event_name }}"
          echo "ref:   ${{ github.ref }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node -v
